name: pduq
channels:
  - conda-forge
  - pycalphad
dependencies:
  - python=3.6
  - pycalphad=0.8
  - numpy
  - scipy
  - sympy=1.4
  - six
  - dask=1.2.2
  - distributed
  - tinydb=3.13.0
  - scikit-learn
  - emcee
  - pyyaml
  - cerberus
  - bibtexparser
  - nose
  - mock
  - twine
  - seaborn
  - flake8
  - espei
